import sharp from "sharp";
import { mkdir, readdir, stat, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const PUBLIC = path.join(ROOT, "public");
const OUT = path.join(PUBLIC, "optimized");
const MANIFEST = path.join(ROOT, "src/lib/image-manifest.ts");

const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png"]);

const RULES = [
  {
    test: /^(colleagues|programmer|three-dark|top-view)/,
    maxWidth: 1920,
    quality: 82,
  },
  {
    test: /html-css/,
    maxWidth: 1400,
    quality: 82,
  },
  {
    test: /^team_/,
    maxWidth: 640,
    quality: 85,
  },
  {
    test: /^project_/,
    maxWidth: 900,
    quality: 85,
  },
  {
    test: /^(map_bg_landscape|japan_photo|bangladesh_photo|hero_illustration|db60b37)/,
    maxWidth: 1400,
    quality: 85,
  },
  {
    test: /KATSL_Logo/,
    maxWidth: 400,
    quality: 90,
    format: "webp",
  },
];

function getRule(filename) {
  return RULES.find((rule) => rule.test.test(filename)) ?? {
    maxWidth: 1200,
    quality: 85,
    format: "webp",
  };
}

async function isFresh(sourcePath, outputPath) {
  try {
    const [sourceStat, outputStat] = await Promise.all([
      stat(sourcePath),
      stat(outputPath),
    ]);
    return outputStat.mtimeMs >= sourceStat.mtimeMs;
  } catch {
    return false;
  }
}

async function createBlurDataUrl(buffer) {
  const blur = await sharp(buffer)
    .resize(16, 16, { fit: "inside" })
    .webp({ quality: 20 })
    .toBuffer();

  return `data:image/webp;base64,${blur.toString("base64")}`;
}

async function optimizeImage(filename) {
  const sourcePath = path.join(PUBLIC, filename);
  const rule = getRule(filename);
  const format = rule.format ?? "webp";
  const outputName = `${path.parse(filename).name}.${format}`;
  const outputPath = path.join(OUT, outputName);
  const publicPath = `/optimized/${outputName}`;

  if (await isFresh(sourcePath, outputPath)) {
    const existing = await sharp(outputPath).toBuffer();
    const blurDataURL = await createBlurDataUrl(existing);
    return { source: `/${filename}`, src: publicPath, blurDataURL };
  }

  let pipeline = sharp(sourcePath).rotate();

  const metadata = await pipeline.metadata();
  if (metadata.width && metadata.width > rule.maxWidth) {
    pipeline = pipeline.resize(rule.maxWidth, null, {
      withoutEnlargement: true,
      fit: "inside",
    });
  }

  const optimized =
    format === "webp"
      ? await pipeline.webp({ quality: rule.quality }).toBuffer()
      : await pipeline.png({ compressionLevel: 9, quality: rule.quality }).toBuffer();

  await writeFile(outputPath, optimized);

  const blurDataURL = await createBlurDataUrl(optimized);
  const before = (await stat(sourcePath)).size;
  const after = optimized.length;

  console.log(
    `  ${filename} -> ${outputName} (${(before / 1024 / 1024).toFixed(1)}MB -> ${(after / 1024).toFixed(0)}KB)`
  );

  return { source: `/${filename}`, src: publicPath, blurDataURL };
}

function writeManifest(entries) {
  const manifest = `// Generated by scripts/optimize-images.mjs — do not edit manually.

export type OptimizedImage = {
  source: string;
  src: string;
  blurDataURL: string;
};

export const imageManifest: Record<string, OptimizedImage> = ${JSON.stringify(
    Object.fromEntries(entries.map((entry) => [entry.source, entry])),
    null,
    2
  )};

export function getOptimizedImage(source: string): OptimizedImage {
  const image = imageManifest[source];
  if (!image) {
    return { source, src: source, blurDataURL: "" };
  }
  return image;
}
`;

  return writeFile(MANIFEST, manifest, "utf8");
}

async function main() {
  await mkdir(OUT, { recursive: true });

  const files = (await readdir(PUBLIC)).filter((file) =>
    IMAGE_EXTENSIONS.has(path.extname(file).toLowerCase())
  );

  console.log("Optimizing images...");
  const entries = [];

  for (const file of files) {
    entries.push(await optimizeImage(file));
  }

  await writeManifest(entries);
  console.log(`Wrote ${entries.length} optimized images to public/optimized/`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
