// Generated by scripts/optimize-images.mjs — do not edit manually.

export type OptimizedImage = {
  source: string;
  src: string;
  blurDataURL: string;
};

export const imageManifest: Record<string, OptimizedImage> = {
  "/KATSL_Logo.3692a9b70d427f6902c5.png": {
    "source": "/KATSL_Logo.3692a9b70d427f6902c5.png",
    "src": "/optimized/KATSL_Logo.3692a9b70d427f6902c5.webp",
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSDoAAAABYFpbe5N/jJyouF7pXYHquGA5aIZgdk5miIgJgDNgiK6/95FjX6nJRQzLfF9L9wNnwCRNpfWOGicRVlA4IDIAAADQAQCdASoQAAQABUB8JbACdADwmsd4AAD+2aYgclxzAxEu80ZzyxSyuDpUtQ4Cd6tAAA=="
  },
  "/bangladesh_photo.png": {
    "source": "/bangladesh_photo.png",
    "src": "/optimized/bangladesh_photo.webp",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQABAABUB8JZACdAEJKazmIDgA/sVk6qu8Du9rWbFRIHiFYYWgk2uitSyEZ0H/br9UpC6LpwOMamzT7tOpzIX/x1gAAA=="
  },
  "/colleagues-discussing-work-project.jpg": {
    "source": "/colleagues-discussing-work-project.jpg",
    "src": "/optimized/colleagues-discussing-work-project.webp",
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsABUB8JZQAAh+XDuFzliAA/usFAx+IJJxFH3CYw3afrNawhbJLYKPU0d9nyR44xa14TkyFaUTt6t9DQ/lgMQfbAAAA"
  },
  "/db60b37bc84379f89ce568b2d99841d7.5ccdace4dc596bbb0e43.png": {
    "source": "/db60b37bc84379f89ce568b2d99841d7.5ccdace4dc596bbb0e43.png",
    "src": "/optimized/db60b37bc84379f89ce568b2d99841d7.5ccdace4dc596bbb0e43.webp",
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4WAoAAAAQAAAADwAABgAAQUxQSFsAAAABuYzof4BRG0mOunvzAj/Km2d+hyFiAqrwnUCK7YGEYAMpFrpExD1GksNIQMYZJwKHQHKAich0h3PV4iQw8jjXDI8RMtEFrlgIgifYJqDiuCgB2lxQLPAnjgIyAFZQOCAaAAAAMAEAnQEqEAAHAAVAfCWkAANwAP7wY1oAAAA="
  },
  "/hero_illustration.png": {
    "source": "/hero_illustration.png",
    "src": "/optimized/hero_illustration.webp",
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoQABAABUB8JaAC7AYto16FBlsAAP7v1zoKT+lSlpIFLx29qUdAcXcrYgNgPxuQQVlvAJG/NgjrcSdT4UWolQf50b5xcQ2bF0XYcQDq09tH+bTB45VQjvpEJkRAESVKXTzCplrd+RYImPMhAAA="
  },
  "/html-css-collage-concept-with-person.jpg": {
    "source": "/html-css-collage-concept-with-person.jpg",
    "src": "/optimized/html-css-collage-concept-with-person.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoQAAsABUB8JYwCdAD8GDfymzAAAP7p14H70Q5KSGG8aJof1FdBjfkXG3+MkBfUYtVs21TaG2AAAA=="
  },
  "/japan_photo.png": {
    "source": "/japan_photo.png",
    "src": "/optimized/japan_photo.webp",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQABAABUB8JZACdADpJ3/cAAAA+katjatB7DT3j/0ng2oCaPwcflpOfZw+6/EWMqlHVPel2465OWq6UiAy2bu9BsltOCJkKAmWUAAA"
  },
  "/map_bg_landscape.png": {
    "source": "/map_bg_landscape.png",
    "src": "/optimized/map_bg_landscape.webp",
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoQABAABUB8JbACdADcBsgAAPyMoQevwhP89mF6KZRoPvkcSp+KIJnvzkwxJBx4cpm/v2QfBaUJlzgpAAA="
  },
  "/programmer-night.jpg": {
    "source": "/programmer-night.jpg",
    "src": "/optimized/programmer-night.webp",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAsABUB8JYgCdH8AD45c9CgAAP10CxW2md4W3pIZLVdoRe0OJO0QMLdQbCnDDjH9+NklOxB0kOVnOE8uQHaQdAAAAA=="
  },
  "/project_ai.png": {
    "source": "/project_ai.png",
    "src": "/optimized/project_ai.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACQAQCdASoQABAABUB8JaQAAueFR9gA/ujmhlgrtk/usDaQAAA="
  },
  "/project_enterprise.png": {
    "source": "/project_enterprise.png",
    "src": "/optimized/project_enterprise.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoQABAABUB8JaQAAp1c1CYAAP7gBkWkUv6GnrqU5VleuxLuRr9H1U04y14TiuQAAAA="
  },
  "/project_mobile.png": {
    "source": "/project_mobile.png",
    "src": "/optimized/project_mobile.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAAAwAQCdASoQABAABUB8JZQAA3AA/u9Z+ebx8vOeQmc0KpJ6pFkoYWFAAAA="
  },
  "/team_aria.png": {
    "source": "/team_aria.png",
    "src": "/optimized/team_aria.webp",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQABAABUB8JZQAAh/EKZ4MywAA/q7r4zdkSMyIO1TYddU12KmKisIDYKAXvJhd0OnnzqXRUyl3qn2AcyZpaXXZNjCUQrRD0IAAAA=="
  },
  "/team_kenshin.png": {
    "source": "/team_kenshin.png",
    "src": "/optimized/team_kenshin.webp",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQABAABUB8JZQAD4tLoG5rlAAA/sN1vrMsJs2eHGUHkMRA2LpzUvZVdw5NzO4gnBtu4R3R46rWHlMbkv8Pkv1iaq9kvjTbXCAAAA=="
  },
  "/team_ren.png": {
    "source": "/team_ren.png",
    "src": "/optimized/team_ren.webp",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQABAABUB8JZwAAiEFfztITAD+jHypVB2S91JjMSZxflJ9IIsb5068bmD2uCfCY5l6D3UsWei17frUgxR7ShqJPncAAA=="
  },
  "/team_yuki.png": {
    "source": "/team_yuki.png",
    "src": "/optimized/team_yuki.webp",
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQABAABUB8JYwAAv9DVri3e+QA/sN1HOY8ARqvQJ3NmTQYdHJ8Z3tVafx8bnoFdIazoz4ozXyY2l67E6rFn9nHIZhaP43fZz0K6qCx1o10GWXgAAA="
  },
  "/three-dark-skinned-guy-chatting-laptop-sitting-sideways-desk-studio-black-background.jpg": {
    "source": "/three-dark-skinned-guy-chatting-laptop-sitting-sideways-desk-studio-black-background.jpg",
    "src": "/optimized/three-dark-skinned-guy-chatting-laptop-sitting-sideways-desk-studio-black-background.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoQAAsABUB8JZQC7AD0EmriX6AA/vDfoC8bYHc5o9VsHzjrrB0cTRbD/S5FlAAA"
  },
  "/top-view-plan-written-black-notepad-lupa-keyboard-light-bulb-pen-black-table.jpg": {
    "source": "/top-view-plan-written-black-notepad-lupa-keyboard-light-bulb-pen-black-table.jpg",
    "src": "/optimized/top-view-plan-written-black-notepad-lupa-keyboard-light-bulb-pen-black-table.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoQAAsABUB8JaQAAjktAAD+40pwXiwcoko45R0IW8xGcJNFKMkD2FDgAAA="
  }
};

export function getOptimizedImage(source: string): OptimizedImage {
  const image = imageManifest[source];
  if (!image) {
    return { source, src: source, blurDataURL: "" };
  }
  return image;
}
